### ISSUE TITLE
Installation Difficulties

### ISSUE THREAD

**Issue by kainszs** [aimat-lab/graph_attention_student#2]
Good morning,

Your installation instructions are no longer up to date. I have noticed the following things:

1. you are using Python 3.10 and not 3.8 as stated in the README.

2. additionally the module `visual_graph_datasets` is needed for the given minimal example.

3. in the minimal example you import

```python
from visual_graph_datasets.utils import dynamic_import
```

instead of

```python
from visual_graph_datasets.util import dynamic_import
```

4. it would be useful if you mentioned which operating system you are using. With Windows 11 and Python 3.10 the module `cairosvg` causes problems.

5. The last line of code also contains errors:

 ```python
print(f'Solubility: {out_pred:.2f}')
```

instead of

 ```python
print(f'Solubility: {out_pred[0]:.2f}')
```

Best, Kai

Addendum:

It is possible to get cairo to run on windows by installing [GTK3-Runtime](https://github.com/tschoonj/GTK-for-Windows-Runtime-Environment-Installer?tab=readme-ov-file)

and inserting the following [code](https://stackoverflow.com/questions/46265677/get-cairosvg-working-in-windows) for the import statement:

```python
import os
import ctypes.util

gtkbin = r “C:\Program Files\GTK3-Runtime Win64\bin”

add_dll_dir = getattr(os, 'add_dll_directory', None)

os.environ['PATH'] = os.pathsep.join((gtkbin, os.environ['PATH']))

if ctypes.util.find_library('libcairo-2') is None:
    raise ImportError(f'Could not find libcairo-2 in the GTK3 runtime directory! {gtkbin}')

```

I hope this helps the next one.

**Comment by the16thpythonist** [comment]
Hello Kai,

Thank you for your comments!

In the next update, I will fix the issues you mentioned and add the missing installation 
instructions to the readme - including the Cairo issues on Windows.

best,
Jonas
