### ISSUE TITLE
TF requirements

### ISSUE THREAD

**Issue by ccoulombe** [aimat-lab/graph_attention_student#3]
Howdy! 

Does the requirement for `tensorflow` *really* need to be `<=2.12.0` ? Or could I use tensorflow 2.15.0 and up ?

Thanks,

**Comment by the16thpythonist** [comment]
Hello,

You can also use tensorflow version >= 2.15.0. Strictly speaking, tensorflow isn't actually needed at all anymore. In the most recent versions we've completely ported the model to pytorch and only left in the tensorflow implementation for compatibility reasons. However, we are planning to remove the tensorflow code and the dependency at some point in the future.

**Comment by ccoulombe** [comment]
Great that is all I needed to know, thank you!
